### ISSUE TITLE
gpu_query

### ISSUE THREAD

**Issue by cindyhfls** [lfads/lfads-run-manager#12]
Hi I am trying the example Lorenz Experiment single session on Mac.

My code broke at query_gpu_status. Can anyone help with it??

Traceback (most recent call last):
  File "run_lfadsqueue.py", line 10, in <module>
    tasks = lq.run_lfads_queue(queue_name, tensorboard_script, task_specs, gpu_list=gpu_list, one_task_per_gpu=True)
  File "/Users/jiaxintu/lfads-run-manager/src/lfadsqueue.py", line 432, in run_lfads_queue
    gpu_status = query_gpu_status()
  File "/Users/jiaxintu/lfads-run-manager/src/lfadsqueue.py", line 107, in query_gpu_status
    '--format=csv,noheader,nounits'])
  File "/Users/jiaxintu/anaconda3/envs/lfads/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/jiaxintu/anaconda3/envs/lfads/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/Users/jiaxintu/anaconda3/envs/lfads/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by djoshea** [comment]
Ah, sorry, somehow I missed this notification. The core issue is that tensorflow GPU is not supported on Mac OS. In this specific instance, the call to `nvidia-smi` is failing, since it exists only on Linux installs of NVIDIA drivers. If you're trying to run on Mac with CPU, it will be slower, though it can be done. In this case you should just run the `lfads_train.sh` script directly rather than using the `lfadsqueue`.
